example:
  property: I AM UBUN
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ostock_dev
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  boot:
    admin:
      client:
        url: http://monitoring-service:8000
