example:
  property: I AM THE DEFAULT
management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: 'true'
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    testWhileIdle: 'true'
    validationQuery: SELECT 1
    platform: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: create
    show-sql: 'true'
