example:
  property: I AM DEV
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ostock_dev_organization
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  boot:
    admin:
      client:
        url: http://localhost:8000
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/